version: "3"

services:
  server:
    image: michailzyusko2001/benefit.backend.monolith:latest
    container_name: benefit.server
    command: 'node dist/main.js'
    env_file:
      - .env.local
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - app-net

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: benefit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "!michail.zyusko_2001!"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - '5432:5432'
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    networks:
      - app-net

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  docker-nest-postgres:
